# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

stages:

  - stage: build
    jobs:
    - job: build
      steps: 
        - script: dotnet build pipelineMvcDemo/pipelineMvcDemo.csproj

  - stage: test
    dependsOn: build
    jobs:
    - job: test
      steps: 
        - script: dotnet test pipelineMvcDemo/pipelineMvcDemo.csproj

  - stage: publish
    dependsOn: test
    jobs:
    - job: publish
      steps: 
        - script: dotnet publish pipelineMvcDemo/pipelineMvcDemo.csproj

name: '$(date:yyyyMMdd)$(rev:rr)'